name: First GitHub Actions Workflow

on: [push]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Hello, World
        run: echo "hello github actions"
      - name: List files
        run: ls -l
